# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c5976af41925d7a46b7e912707a87e469b3e4ae50430a060aa2d6f99ff4b0d7d875f7643780b6ddd51bf5fe9da7f1cb4201ff8292d4ef30fa1faab89885115bd

test:
  secret_key_base: 0f3b053f088eb80494cafa1ad677cfed603115b85af4472b5abd5e6e268fc334db2a57910286b6d287c2ba8775cd39c55417f64296f512ed6a9e4725a39289c4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
